// Code generated by cmd/cgo; DO NOT EDIT.

//line main.go:1:1
package main

//int sum(int a, int b) { return a+b; }
import _ "unsafe"

func main() {
    println(( /*line :7:13*/_Cfunc_sum /*line :7:17*/)(1, 1))
}